"""Shared thresholds and defaults for DroneCaptureOps Gym."""

DEFAULT_DOMAIN = "solar"
DEFAULT_SEED = 7
DEFAULT_MAX_STEPS = 40

MIN_ALTITUDE_M = 2.0
MAX_ALTITUDE_M = 60.0
MAX_SPEED_MPS = 12.0
MIN_BATTERY_TO_RETURN_PCT = 20.0
INVALID_ACTION_LIMIT = 3

TAKEOFF_BATTERY_COST = 1.2
LAND_BATTERY_COST = 0.4
HOVER_BATTERY_COST_PER_S = 0.015
FLIGHT_BATTERY_COST_PER_M = 0.045
CAPTURE_BATTERY_COST = 0.25

THERMAL_EFFECTIVE_RANGE_M = 48.0
RGB_EFFECTIVE_RANGE_M = 34.0
GOOD_CAPTURE_THRESHOLD = 0.68
